apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: my-container
    image: quay.io/fromani/numalign
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c"]
    args: [ "while true; do numalign; sleep 100000; done;" ]
    resources:
      limits:
        cpu: 1
        memory: 20Mi
      requests:
        cpu: 1
        memory: 20Mi
